/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _10 = '._bfhk13q2{background-color:blue}';
const _1 = '._syaz5scu{color:red}';
const _0 = '._189e1y44{border-width:4px}';
const _9 = '._2rkogktf{border-radius:20px}';
const _8 = '._18u019bv{margin-left:10px}';
const _7 = '._otyr19bv{margin-bottom:10px}';
const _6 = '._2hwx19bv{margin-right:10px}';
const _5 = '._19pk19bv{margin-top:10px}';
const _4 = '._19bv19bv{padding-left:10px}';
const _3 = '._n3td19bv{padding-bottom:10px}';
const _2 = '._u5f319bv{padding-right:10px}';
const _ = '._ca0q19bv{padding-top:10px}';
const TEN = 10;
const PX = 'px';
const PADDING = `${TEN}${PX}`;
const COLOR = 'red';
const PALETTE = {
	brand: 'blue',
	spacing: {
		sm: 4,
	},
};
const DOUBLE = TEN + TEN;
const styles = null;
<CC>
	<CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _0, _1, _10]}</CS>
	{
		<div
			className={ax([
				'_ca0q19bv _u5f319bv _n3td19bv _19bv19bv _19pk19bv _2hwx19bv _otyr19bv _18u019bv _2rkogktf _189e1y44 _syaz5scu _bfhk13q2',
			])}
		/>
	}
</CC>;
