/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._30l3r3uz:hover{color:#000}";
const _ = "._syazruxl{color:orange}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2]}</CS>
  {<div className={ax(["_syazruxl _30l3r3uz"])}>Hello</div>}
</CC>;
