/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const _6 = "._gc90b3bt:active:after{content:\"\"}";
const _5 = "._91x1idpf:active:after{left:0}";
const _4 = "._1r9x1o36:active{outline-width:medium}";
const _3 = "._1ohyglyw:active{outline-style:none}";
const _2 = "._1q5t1r31:active{outline-color:currentColor}";
const _ = "._1e0c1txw{display:flex}";
const themedUnderline = {
  '&::after': {
    left: 0,
    content: "''"
  }
};
const tabStyles = null;
export const Tab = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return /*#__PURE__*/_jsxs(CC, {
    children: [/*#__PURE__*/_jsx(CS, {
      children: [_, _2, _3, _4, _5, _6]
    }), /*#__PURE__*/_jsx(C, {
      ...__cmplp,
      style: __cmpls,
      ref: __cmplr,
      className: ax(["_1e0c1txw _1q5t1r31 _1ohyglyw _1r9x1o36 _91x1idpf _gc90b3bt", __cmplp.className])
    })]
  });
});
if (process.env.NODE_ENV !== 'production') {
  Tab.displayName = 'Tab';
}
