/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "@keyframes k1j8refv{0%{transform:rotate(0deg)}to{transform:rotate(1turn)}}";
const _ = "._y44v32og{animation:k1j8refv 1.5s linear infinite}";
const spin = null;
export const Component = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_y44v32og", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Component.displayName = 'Component';
}
