/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _4 = '@media (min-width:64rem){._qiln1gzg{grid-area:main}}';
const _3 = '._30l313q2:hover{color:blue}';
const _2 = '._syaz5scu{color:red}';
const _ = '._19it19z9{border:1px solid green}';
const obj1 = null;
const tpl1 = null;
<>
	<CC>
		<CS>{[_, _2, _3, _4]}</CS>
		{<div className={ax(['_19it19z9 _syaz5scu _30l313q2 _qiln1gzg'])} />}
	</CC>
	<CC>
		<CS>{[_, _2, _3, _4]}</CS>
		{<div className={ax(['_19it19z9 _syaz5scu _30l313q2 _qiln1gzg'])} />}
	</CC>
</>;
