/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _3 = '._p12f1rkg{max-width:var(--_1gljcou)}';
const _2 = '._1ul91rkg{min-width:var(--_1gljcou)}';
const _ = '._1bsb1rkg{width:var(--_1gljcou)}';
export const BadgeSkeleton = forwardRef(
	({ as: C = 'span', style: __cmpls, ...__cmplp }, __cmplr) => {
		if (__cmplp.innerRef) {
			throw new Error("Please use 'ref' instead of 'innerRef'.");
		}
		return (
			<CC>
				<CS>{[_, _2, _3]}</CS>
				<C
					{...__cmplp}
					style={{
						...__cmpls,
						'--_1gljcou': ix(__cmplp.width),
					}}
					ref={__cmplr}
					className={ax(['_1bsb1rkg _1ul91rkg _p12f1rkg', __cmplp.className])}
				/>
			</CC>
		);
	},
);
if (process.env.NODE_ENV !== 'production') {
	BadgeSkeleton.displayName = 'BadgeSkeleton';
}
export const View = () => <BadgeSkeleton />;
