/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._30l313q2:hover{color:blue}";
const _ = "._syaz5scu{color:red}";
const baseStyles = {
  color: 'red'
};
const hoverStyles = {
  '&:hover': {
    color: 'blue'
  }
};
export const Component = ({
  isActive,
  children
}) => {
  return <CC>
    <CS>{[_, _2]}</CS>
    {<div className={ax(["_syaz5scu", isActive && "_30l313q2"])}>
			{children}
		</div>}
  </CC>;
};
