/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _4 = '._k48pbfng{font-weight:500}';
const _3 = '._1wyb1crf{font-size:9pt}';
const _2 = '._syaz13q2{color:blue}';
const _ = '._19it1nsd{border:1px solid blue}';
const bgColor = 'blue';
const fontSize = 12;
const fontStyling = {
	weight: 500,
};
const sizes = {
	mixin1: () => `1px solid ${bgColor}`,
	mixin2: () => ({
		fontSize,
	}),
	mixin3: function () {
		return {
			fontWeight: fontStyling.weight,
		};
	},
};
const styles2 = null;
<CC>
	<CS>{[_, _2, _3, _4]}</CS>
	{<div className={ax(['_19it1nsd _syaz13q2 _1wyb1crf _k48pbfng'])} />}
</CC>;
