/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _9 = '._irr3u67f:hover{background-color:#fff}';
const _8 = '._30l313q2:hover{color:blue}';
const _7 = '._qmv617nt:hover ._qmv617nt:focus{background-color:gray}';
const _6 = '._1vpk1cnh:hover ._1vpk1cnh:focus{color:purple}';
const _5 = '._f8pjbf54:focus{color:green}';
const _4 = '._vn89ftgi:focus{border-radius:8px}';
const _3 = '._bfhkr3uz{background-color:#000}';
const _2 = '._syaz5scu{color:red}';
const _ = '._2rko1y44{border-radius:4px}';
const styles = null;
<CC>
	<CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9]}</CS>
	{
		<div
			className={ax([
				'_2rko1y44 _syaz5scu _bfhkr3uz _vn89ftgi _f8pjbf54 _1vpk1cnh _qmv617nt _30l313q2 _irr3u67f',
			])}
		/>
	}
</CC>;
