/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _6 = "@media (min-width:50em){._r5zo1r31:focus{outline-color:currentColor}._s3beglyw:focus{outline-style:none}._10t01o36:focus{outline-width:medium}}";
const _5 = "._30l3u67f:hover{color:#fff}";
const _4 = "._hkegnqa1>span{text-decoration-style:solid}";
const _3 = "._16fv8stv>span{text-decoration-line:underline}";
const _2 = "._1h9x1r31>span{text-decoration-color:currentColor}";
const _ = "._syaz143u{color:navy}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2, _3, _4, _5, _6]}</CS>
  {<div className={ax(["_syaz143u _1h9x1r31 _16fv8stv _hkegnqa1 _30l3u67f _r5zo1r31 _s3beglyw _10t01o36"])}>
    <span>Nested</span>
  </div>}
</CC>;
