/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "._1itk11i6{background-image:linear-gradient(to right,var(--ds-background-neutral,#091e420f) 10%,var(--ds-background-neutral-subtle,#00000000) 30%,var(--ds-background-neutral,#091e420f) 50%)}";
const Box = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1itk11i6", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Box.displayName = 'Box';
}
export const Component = () => <Box />;
