/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _6 = "._u5f31y44{padding-right:4px}";
const _5 = "._19bv1y44{padding-left:4px}";
const _4 = "._19bvftgi{padding-left:8px}";
const _3 = "._n3tdftgi{padding-bottom:8px}";
const _2 = "._u5f3ftgi{padding-right:8px}";
const _ = "._ca0qftgi{padding-top:8px}";
const padding = '8px';
const large = 8;
const small = 4;
const Cell = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    first,
    last,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi", __cmplp.first ? "_19bvftgi" : "_19bv1y44", __cmplp.last ? "_u5f3ftgi" : "_u5f31y44", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Cell.displayName = 'Cell';
}
export const Component = ({
  first,
  last
}) => <Cell first={first} last={last}>
    Content
  </Cell>;
