enableScripts: true

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  atlassian:
    npmRegistryServer: 'https://packages.atlassian.com/artifactory/api/npm/atlassian-npm'
  atlassiansox:
    npmRegistryServer: 'https://packages.atlassian.com/artifactory/api/npm/atlassian-npm-sox'
