disallowed-methods = [
  # use parking_lot
  "std::sync::Mutex::new",
  "std::sync::RwLock::new",
  "std::sync::Condvar::new",
  "std::sync::Once::new",
]
disallowed-types = ["Mutex", "RwLock", "Condvar", "Once"]
