/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _8 = "._19bv19bv{padding-left:10px}";
const _7 = "._n3td19bv{padding-bottom:10px}";
const _6 = "._u5f319bv{padding-right:10px}";
const _5 = "._ca0q19bv{padding-top:10px}";
const _4 = "._18u019bv{margin-left:10px}";
const _3 = "._otyr19bv{margin-bottom:10px}";
const _2 = "._2hwx19bv{margin-right:10px}";
const _ = "._19pk19bv{margin-top:10px}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2, _3, _4, _5, _6, _7, _8]}</CS>
  {<div className={ax(["_19pk19bv _2hwx19bv _otyr19bv _18u019bv _ca0q19bv _u5f319bv _n3td19bv _19bv19bv"])}>Hello</div>}
</CC>;
