/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _5 = "._19bv7vkz{padding-left:1pc}";
const _4 = "._n3td7vkz{padding-bottom:1pc}";
const _3 = "._u5f37vkz{padding-right:1pc}";
const _2 = "._ca0q7vkz{padding-top:1pc}";
const _ = "._syazu67f{color:#fff}";
const base = null;
const padding = null;
export const Component = () => <CC>
  <CS>{[_, _2, _3, _4, _5]}</CS>
  {<div className={ax(["_syazu67f", "_ca0q7vkz _u5f37vkz _n3td7vkz _19bv7vkz"])}>
    Hello
  </div>}
</CC>;
