/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _6 = '._30l35scu:hover{color:red}';
const _5 = '._syaz13q2{color:blue}';
const _4 = '._19bvftgi{padding-left:8px}';
const _3 = '._n3tdftgi{padding-bottom:8px}';
const _2 = '._u5f3ftgi{padding-right:8px}';
const _ = '._ca0qftgi{padding-top:8px}';
const PADDING = 8;
const BLUE = 'blue';
<>
	<CC>
		<CS>{[_, _2, _3, _4, _5]}</CS>
		{<div xcss={'_ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi _syaz13q2'} />}
	</CC>
	<CC>
		<CS>{[_6]}</CS>
		{<button data-test xCss={'_30l35scu'} />}
	</CC>
</>;
