/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _3 = '._k48p1693{font-weight:900}';
const _2 = '._syazr3uz{color:#000}';
const _ = '._bfhku67f{background-color:#fff}';
const styles = {
	default: null,
	success: null,
	fail: null,
	bg: null,
};
const Component = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	return (
		<CC>
			<CS>{[_, _2, _3]}</CS>
			<C
				{...__cmplp}
				style={__cmpls}
				ref={__cmplr}
				className={ax(['_bfhku67f _syazr3uz _k48p1693', __cmplp.className])}
			/>
		</CC>
	);
});
if (process.env.NODE_ENV !== 'production') {
	Component.displayName = 'Component';
}
export const View = () => <Component />;
