/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _16 = "._c3k8ze3t p{margin-left:var(--ds-space-0,0)}";
const _15 = "._q0a5ze3t p{margin-bottom:var(--ds-space-0,0)}";
const _14 = "._11pqze3t p{margin-right:var(--ds-space-0,0)}";
const _13 = "._clfdze3t p{margin-top:var(--ds-space-0,0)}";
const _12 = "._1rgf12x7 input{margin-left:var(--ds-space-075,6px)}";
const _11 = "._x5bdze3t input{margin-bottom:var(--ds-space-0,0)}";
const _10 = "._12hv12x7 input{margin-right:var(--ds-space-075,6px)}";
const _1 = "._2x4gze3t input{margin-top:var(--ds-space-0,0)}";
const _0 = "._15pj1txw label{display:flex}";
const _9 = "._1eq11h6o label{align-items:center}";
const _8 = "._dlecu2gc label{gap:var(--ds-space-100,8px)}";
const _7 = "._bfhk11bn{background-color:var(--ds-background-accent-gray-subtlest,#f1f2f4)}";
const _6 = "._1bsb1osq{width:100%}";
const _5 = "._4t3i1jfw{height:var(--ds-space-500,40px)}";
const _4 = "._1e0c1txw{display:flex}";
const _3 = "._4cvr1h6o{align-items:center}";
const _2 = "._n7zl176a{border-bottom:var(--ds-space-025,2px) solid var(--ds-border,#091e4224)}";
const _ = "._zulpu2gc{gap:var(--ds-space-100,8px)}";
const layoutStyles = {
  alignItems: 'center',
  display: 'flex',
  gap: `${"var(--ds-space-100, 8px)"}`
};
const checkboxStyles = {
  ...layoutStyles,
  borderBottom: `${"var(--ds-space-025, 2px)"} solid ${"var(--ds-border, #091E4224)"}`,
  height: `${"var(--ds-space-500, 40px)"}`,
  width: '100%'
};
const getBackgroundColor = (checked, disabled) => {
  if (disabled) {
    return "var(--ds-background-accent-gray-subtlest, #F1F2F4)";
  }
  return checked ? "var(--ds-background-accent-blue-subtlest, #E9F2FF)" : 'transparent';
};
const ProjectCheckbox = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _0, _1, _10, _11, _12, _13, _14, _15, _16]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_zulpu2gc _n7zl176a _4cvr1h6o _1e0c1txw _4t3i1jfw _1bsb1osq _bfhk11bn _dlecu2gc _1eq11h6o _15pj1txw _2x4gze3t _12hv12x7 _x5bdze3t _1rgf12x7 _clfdze3t _11pqze3t _q0a5ze3t _c3k8ze3t", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  ProjectCheckbox.displayName = 'ProjectCheckbox';
}
export const Component = () => <ProjectCheckbox checked disabled={false}>
		<label>
			<input type="checkbox" />
			<p>Description</p>
		</label>
	</ProjectCheckbox>;
