/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const styles = null;
const cond = true;
<>
	<div xcss={styles} />
	<div xcss={cond ? styles : null} />
	<div xcss={Math.random() > 0.5 ? styles : styles} />
</>;
