/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { forwardRef } from 'react';
import { token } from '@atlaskit/tokens';
const _ = "._19itglyw{border:none}";
const _1 = "._19itzgxb{border:1px solid var(--ds-border,#091e4224)}";
const Wrapper = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr)=>{
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[
        _,
        _1
      ]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax([__cmplp.isSummaryView ? "_19itglyw" : "_19itzgxb", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Wrapper.displayName = 'Wrapper';
}
export const Component = ()=><Wrapper isSummaryView={false} />;
