/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._syazwwip{color:#292a2e}";
const _ = "._1e0c1txw{display:flex}";
const styles = {
  container: "_1e0c1txw",
  textBold: "_syazwwip"
};
export const Component = () => <CC>
    <CS>{[_, _2]}</CS>
    {<div className={ax([styles.container])}>
    <CC>
    <CS>{[_, _2]}</CS>
    {<span className={ax([styles.textBold])}>Content</span>}
  </CC>
  </div>}
  </CC>;
