[package]
name = "atlaspack_plugin_transformer_inline"
version = "0.1.0"
authors = ["Monica Olejniczak <monica.j.olejniczak@gmail.com>"]
edition = "2021"
description = "Inline transformer plugin for the Atlaspack Bundler"

[dependencies]
atlaspack_core = { path = "../atlaspack_core" }

anyhow = "1"

[dev-dependencies]
atlaspack_filesystem = { path = "../atlaspack_filesystem" }
