/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "._16qs1m9i{box-shadow:inset 0 -1px 0 0 var(--_lnnecg)}";
const token = (key, fallback) => fallback;
const border = null;
const Component = () => <CC>
    <CS>{[_]}</CS>
    {<div className={ax(["_16qs1m9i"])} style={{
    "--_lnnecg": ix(token('color.border'))
  }}>
		<span>Content with border</span>
	</div>}
  </CC>;
export default Component;
