/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { gridSize } from './constants';
const _10 = "._1o9zidpf{flex-shrink:0}";
const _1 = "._4t3i1tcg{height:24px}";
const _0 = "._1bsb7vkz{width:1pc}";
const _9 = "._1pqwzwfg td{padding-left:2pc}";
const _8 = "._6aut1tcg td{padding-bottom:24px}";
const _7 = "._owip7vkz td{padding-right:1pc}";
const _6 = "._p4liftgi td{padding-top:8px}";
const _5 = "._13l9h2mm td:first-child{position:relative}";
const _4 = "._2hwx1wug{margin-right:auto}";
const _3 = "._18u01wug{margin-left:auto}";
const _2 = "._p12f1lit{max-width:10pc}";
const _ = "._1ul9ys9h{min-width:5pc}";
const Container = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1ul9ys9h _p12f1lit _18u01wug _2hwx1wug _13l9h2mm _p4liftgi _owip7vkz _6aut1tcg _1pqwzwfg", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Container.displayName = 'Container';
}
const Logo = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_0, _1, _10]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1bsb7vkz _4t3i1tcg _1o9zidpf", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Logo.displayName = 'Logo';
}
export const Component = () => <Container>
    <Logo />
    <table>
      <tbody>
        <tr>
          <td>First</td>
          <td>Second</td>
        </tr>
      </tbody>
    </table>
  </Container>;
