/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const styles = {
  button: "_18zrpxbi"
};
export const Component = () => <div className={styles.button()}>Content</div>;
