/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '._j7hqc836{animation-name:k13hl4np}';
const _ = '@keyframes k13hl4np{0%{opacity:0;color:red}to{opacity:1;color:blue}}';
const from = {
	opacity: 0,
	color: 'red',
};
const to = {
	opacity: 1,
	color: 'blue',
};
const fade = null;
<CC>
	<CS>{[_, _2]}</CS>
	{<div className={ax(['_j7hqc836'])} />}
</CC>;
