/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _33 = '._1s7zidpf{border-right:0}';
const _32 = '._x3dolf8h{border-top:2px solid blue}';
const _31 = '._14hblf93{scroll-padding-inline:11px 9pt}';
const _30 = '._19mwbwzh{scroll-margin-block:5px 6px}';
const _29 = '._1rjcbwzh{padding-block:5px 6px}';
const _28 = '._195g177e{margin-inline:10px 20px}';
const _27 = '._189ekyy5{border-width:1px 2px 3px 4px}';
const _26 = '._1h6dg5z9{border-color:red green}';
const _25 = '._qiwuzp6i{view-timeline:my-view block}';
const _24 = '._1un94zh1{scroll-timeline:my-tl x}';
const _23 = '._1skx1dpk{contain-intrinsic-size:75pt 200px}';
const _22 = '._ylxrk4sw{container:layout inline-size}';
const _21 = '._3fcw1i3c{text-wrap:balance pretty}';
const _20 = '._10fp1h6o{justify-self:center}';
const _19 = '._1wpz1fhb{align-self:stretch}';
const _18 = '._6a6zh9n0{justify-items:end}';
const _17 = '._4cvrv2br{align-items:start}';
const _16 = '._1bah1yb4{justify-content:space-between}';
const _15 = '._ae4v1h6o{align-content:center}';
const _14 = '._8c5x1emu{overscroll-behavior:contain auto}';
const _13 = '._1bh4146l{scroll-padding:7px 8px 9px 10px}';
const _12 = '._19kckyy5{scroll-margin:1px 2px 3px 4px}';
const _11 = '._1r04kyy5{inset:1px 2px 3px 4px}';
const _10 = '._qtt81ori{list-style:square inside url(a.png)}';
const _1 = '._ajmm1khm{text-decoration-style:wavy}';
const _0 = '._1hms8stv{text-decoration-line:underline}';
const _9 = '._4bfu1vbt{text-decoration-color:#123}';
const _8 = '._yxz31yho{columns:200px 3}';
const _7 = '._zulp177e{gap:10px 20px}';
const _6 = '._18m91wug{overflow-y:auto}';
const _5 = '._1reo15vq{overflow-x:hidden}';
const _4 = '._19it5xv8{border:1px dashed #000}';
const _3 = '._12y319bv{outline-width:10px}';
const _2 = '._1qu2nqa1{outline-style:solid}';
const _ = '._12ji5scu{outline-color:red}';
const styles = null;
<CC>
	<CS>
		{[
			_,
			_2,
			_3,
			_4,
			_5,
			_6,
			_7,
			_8,
			_9,
			_0,
			_1,
			_10,
			_11,
			_12,
			_13,
			_14,
			_15,
			_16,
			_17,
			_18,
			_19,
			_20,
			_21,
			_22,
			_23,
			_24,
			_25,
			_26,
			_27,
			_28,
			_29,
			_30,
			_31,
			_32,
			_33,
		]}
	</CS>
	{
		<div
			className={ax([
				'_12ji5scu _1qu2nqa1 _12y319bv _19it5xv8 _1reo15vq _18m91wug _zulp177e _yxz31yho _4bfu1vbt _1hms8stv _ajmm1khm _qtt81ori _1r04kyy5 _19kckyy5 _1bh4146l _8c5x1emu _ae4v1h6o _1bah1yb4 _4cvrv2br _6a6zh9n0 _1wpz1fhb _10fp1h6o _3fcw1i3c _ylxrk4sw _1skx1dpk _1un94zh1 _qiwuzp6i _1h6dg5z9 _189ekyy5 _195g177e _1rjcbwzh _19mwbwzh _14hblf93 _x3dolf8h _1s7zidpf',
			])}
		/>
	}
</CC>;
