[package]
name = "atlassian_swc_compiled_css"
version = "0.0.1"
edition = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "emit_fixtures"
path = "bin/emit_fixtures.rs"

[dependencies]
swc_core                       = { workspace = true, features = ["ecma_plugin_transform"] }
swc_common                     = { workspace = true, features = ["concurrent"] }
swc_atoms                      = { workspace = true }
swc_ecma_ast                   = { workspace = true }
swc_ecma_parser                = { workspace = true }
swc_ecma_utils                 = { workspace = true }
swc_ecma_visit                 = { workspace = true }
swc_ecma_codegen               = { workspace = true }
serde                          = { workspace = true, features = ["derive"]}
serde_json                     = { workspace = true }
once_cell                      = { workspace = true }
rustc-hash                     = "1.1"
xxhash-rust                    = { version = "0.8", features = ["xxh3"] }
swc_plugin_macro               = { workspace = true, optional = true }
napi-derive                    = { workspace = true }
napi                           = { workspace = true }

[dev-dependencies]
swc_ecma_codegen               = { workspace = true }
swc_ecma_parser                = { workspace = true }
swc_common                     = { workspace = true }

[features]
default = []
plugin = ["swc_plugin_macro"]
napi = []
