/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '._j7hq17bf{animation-name:k1sa9y38}';
const _ = '@keyframes k1sa9y38{0%{opacity:0}to{opacity:1}}';
const kf = null;
const a = null;
const b = null;
<>
	<CC>
		<CS>{[_, _2]}</CS>
		{<div className={ax(['_j7hq17bf'])} />}
	</CC>
	<CC>
		<CS>{[_, _2]}</CS>
		{<div className={ax(['_j7hq17bf'])} />}
	</CC>
</>;
