/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '._30l313q2:hover{color:blue}';
const _ = '._syaz5scu{color:red}';
const Button = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	return (
		<CC>
			<CS>{[_, _2]}</CS>
			<C
				{...__cmplp}
				style={__cmpls}
				ref={__cmplr}
				className={ax(['_syaz5scu _30l313q2', __cmplp.className])}
			/>
		</CC>
	);
});
if (process.env.NODE_ENV !== 'production') {
	Button.displayName = 'Button';
}
export const Btn = () => <Button />;
