/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '._1u2o13q2 >span:first-type-of:hover{color:blue}';
const _ = '._1oey5scu >span:first-type-of{color:red}';
const styles = null;
<CC>
	<CS>{[_, _2]}</CS>
	{<div className={ax(['_1oey5scu _1u2o13q2'])} />}
</CC>;
