/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _3 = '._30l35scu:hover{color:red}';
const _2 = '._30l313q2:hover{color:blue}';
const _ = '._1wyb1crf{font-size:9pt}';
const C = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { isActive, ...__cmpldp } = __cmplp;
	return (
		<CC>
			<CS>{[_, _2, _3]}</CS>
			<C
				{...__cmpldp}
				style={__cmpls}
				ref={__cmplr}
				className={ax([
					'_1wyb1crf',
					__cmplp.isActive ? '_30l313q2' : '_30l35scu',
					__cmplp.className,
				])}
			/>
		</CC>
	);
});
if (process.env.NODE_ENV !== 'production') {
	C.displayName = 'C';
}
export const View = () => <C />;
