[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "atlaspack-dev-dep-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
atlaspack-resolver = { path = "../node-resolver-rs" }
es-module-lexer = { workspace = true }
serde_json = { workspace = true }
rayon = { workspace = true }
glob = { workspace = true }
xxhash-rust = { workspace = true }
