[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "atlaspack-dev-dep-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
atlaspack-resolver = { path = "../node-resolver-rs" }
es-module-lexer = { git = "https://github.com/devongovett/es-module-lexer" }
serde_json = "1.0.91"
rayon = "1.7.0"
glob = "0.3.1"
xxhash-rust = "0.8.12"
