/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _7 = '._1yyjkb7n{-webkit-line-clamp:1}';
const _6 = '._1yyj11wp{-webkit-line-clamp:3}';
const _5 = '._1hmsglyw{text-decoration-line:none}';
const _4 = '._1hms1911{text-decoration-line:line-through}';
const _3 = '._syaz5scu{color:red}';
const _2 = '._syaz13q2{color:blue}';
const _ = '._1wyb1ul9{font-size:30px}';
const Component = forwardRef(({ as: C = 'button', style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { isPrimary, isDone, isClamped, ...__cmpldp } = __cmplp;
	return (
		<CC>
			<CS>{[_, _2, _3, _4, _5, _6, _7]}</CS>
			<C
				{...__cmpldp}
				style={__cmpls}
				ref={__cmplr}
				className={ax([
					'_1wyb1ul9',
					__cmplp.isPrimary ? '_syaz13q2' : '_syaz5scu',
					__cmplp.isDone ? '_1hms1911' : '_1hmsglyw',
					__cmplp.isClamped ? '_1yyj11wp' : '_1yyjkb7n',
					__cmplp.className,
				])}
			/>
		</CC>
	);
});
if (process.env.NODE_ENV !== 'production') {
	Component.displayName = 'Component';
}
export const View = () => <Component />;
