/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _ = '._syaz5scu{color:red}';
const styles = null;
<CC>
	<CS>{[_]}</CS>
	{<div className={ax(['_syaz5scu'])} />}
</CC>;
