/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _20 = '._21 ._8e32b3bt{content:""}';
const _19 = '._22 ._1aif2320{content:"\u2728"}';
const _18 = '._20 ._dqocn7od{content:unset}';
const _17 = '._19 ._kyq719ly{content:revert}';
const _16 = '._18 ._ox6v4jg8{content:normal}';
const _15 = '._17 ._1do11kw7{content:inherit}';
const _14 = '._16 ._17yjbbkt{content:open-quote counter(chapter_counter)}';
const _13 = '._15 ._13gv16xt{content:no-close-quote}';
const _12 = '._14 ._1gw4qmeg{content:no-open-quote}';
const _11 = '._13 ._1erv1lzr{content:close-quote}';
const _10 = '._12 ._yz5n12u0{content:open-quote}';
const _1 = '._11 ._1sv1f7m1{content:attr(value string)}';
const _0 = '._10 ._11jd1td3{content:counters(section_counter,".",decimal-leading-zero)}';
const _9 = '._09 ._1vjjgvpy{content:counters(section_counter,".")}';
const _8 = '._08 ._tc0r17sh{content:counter(chapter_counter,upper-roman)}';
const _7 = '._07 ._1g4mlfyt{content:counter(chapter_counter)}';
const _6 = '._06 ._4g5v1dlo{content:"prefix"}';
const _5 = '._05 ._10o613au{content:url(http://www.example.com/test.png)/"This is the alt text"}';
const _4 = '._04 ._124v19iq{content:image-set("image1x.png" 1x,"image2x.png" 2x)}';
const _3 = '._03 ._qi2v1f55{content:linear-gradient(#e66465,#9198e5)}';
const _2 = '._02 ._1gdz165a{content:url(http://www.example.com/test.png)}';
const _ = '._01 ._1sagglyw{content:none}';
const styles = null;
<CC>
	<CS>
		{[
			_,
			_2,
			_3,
			_4,
			_5,
			_6,
			_7,
			_8,
			_9,
			_0,
			_1,
			_10,
			_11,
			_12,
			_13,
			_14,
			_15,
			_16,
			_17,
			_18,
			_19,
			_20,
		]}
	</CS>
	{
		<div
			className={ax([
				'_1sagglyw _1gdz165a _qi2v1f55 _124v19iq _10o613au _4g5v1dlo _1g4mlfyt _tc0r17sh _1vjjgvpy _11jd1td3 _1sv1f7m1 _yz5n12u0 _1erv1lzr _1gw4qmeg _13gv16xt _17yjbbkt _1do11kw7 _ox6v4jg8 _kyq719ly _dqocn7od _1aif2320 _8e32b3bt',
			])}
		/>
	}
</CC>;
