/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _5 = '._syazr3uz{color:#000}';
const _4 = '._bfhku67f{background-color:#fff}';
const _3 = '._syazu67f{color:#fff}';
const _2 = '._bfhkr3uz{background-color:#000}';
const _ = '._1wyb1ul9{font-size:30px}';
const dark = null;
const light = null;
const Component = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { isDark, ...__cmpldp } = __cmplp;
	return (
		<CC>
			<CS>{[_, _2, _3, _4, _5]}</CS>
			<C
				{...__cmpldp}
				style={__cmpls}
				ref={__cmplr}
				className={ax([
					'_1wyb1ul9',
					__cmplp.isDark ? '_bfhkr3uz _syazu67f' : '_bfhku67f _syazr3uz',
					__cmplp.className,
				])}
			/>
		</CC>
	);
});
if (process.env.NODE_ENV !== 'production') {
	Component.displayName = 'Component';
}
export const View = () => <Component />;
