/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
export const Component = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_vchh1ntv", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  Component.displayName = 'Component';
}
