/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _9 = "._u5f31y44{padding-right:4px}";
const _8 = "._u5f3ftgi{padding-right:8px}";
const _7 = "._19bv1y44{padding-left:4px}";
const _6 = "._19bvftgi{padding-left:8px}";
const _5 = "._1e0c1o8l{display:inline-block}";
const _4 = "._19bvidpf{padding-left:0}";
const _3 = "._n3tdidpf{padding-bottom:0}";
const _2 = "._u5f3idpf{padding-right:0}";
const _ = "._ca0qidpf{padding-top:0}";
const gridSize = 8;
const HeadingCellWrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    first,
    last,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_ca0qidpf _u5f3idpf _n3tdidpf _19bvidpf _1e0c1o8l", __cmplp.first ? "_19bvftgi" : "_19bv1y44", __cmplp.last ? "_u5f3ftgi" : "_u5f31y44", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  HeadingCellWrapper.displayName = 'HeadingCellWrapper';
}
export const Component = ({
  first,
  last
}) => <HeadingCellWrapper first={first} last={last}>
    content
  </HeadingCellWrapper>;
