/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _5 = '._30l35scu:hover{color:red}';
const _4 = '._vn89ftgi:focus{border-radius:8px}';
const _3 = '._bfhkbf54{background-color:green}';
const _2 = '._19itak0l{border:2px solid red}';
const _ = '._syaz13q2{color:blue}';
const BLUE = 'blue';
const SIZE = 2;
const theme = {
	col: 'red',
};
const COLORS = {
	bg: 'white',
};
const getGreen = () => 'green';
const a = null;
const b = null;
const c = null;
const d = null;
<>
	<CC>
		<CS>{[_]}</CS>
		{<div className={ax(['_syaz13q2'])} />}
	</CC>
	<CC>
		<CS>{[_2]}</CS>
		{<div className={ax(['_19itak0l'])} />}
	</CC>
	<CC>
		<CS>{[_3]}</CS>
		{<div className={ax(['_bfhkbf54'])} />}
	</CC>
	<CC>
		<CS>{[_4, _5]}</CS>
		{<div className={ax(['_vn89ftgi _30l35scu'])} />}
	</CC>
</>;
