/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._bfhk1j28{background-color:transparent}";
const _ = "._syaz5scu{color:red}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2]}</CS>
  {<div className={ax(["_syaz5scu _bfhk1j28"])}>Hello</div>}
</CC>;
