/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "@property --my-color{syntax:\"<color>\";inherits:var(--_ikpmwb);initial-value:#000}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax([])} style={{
    "--_ikpmwb": ix(false)
  }}>Hello</div>}
</CC>;
