/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "._syaz5scu{color:red}";
export const Styled = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  return <CC>
        <CS>{[_]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_syaz5scu", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Styled.displayName = 'Styled';
}
