/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
export const blank = null;
export const text = null;
export const quoted = null;
export const arrow = null;
