/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
import styled, { css } from 'styled-components';

// Mixed patterns: css2 from @compiled/react and css from styled-components
const _10 = "._p12fuuw1{max-width:200px}";
const _1 = "._18m915vq{overflow-y:hidden}";
const _0 = "._1reo15vq{overflow-x:hidden}";
const _9 = "._syaz1d6m{color:#333}";
const _8 = "._bfhk1kw7{background-color:inherit}";
const _7 = "._2hwx1y44{margin-right:4px}";
const _6 = "._19bvidpf{padding-left:0}";
const _5 = "._n3tdyh40{padding-bottom:2px}";
const _4 = "._u5f3idpf{padding-right:0}";
const _3 = "._ca0qyh40{padding-top:2px}";
const _2 = "._4cvr1h6o{align-items:center}";
const _ = "._1e0c1txw{display:flex}";
const referencedObjectsContainerStyles = null;
const maxWidth2 = null;
const plainTextStyles = null;

// Styled component using css template literal
const LozengeLink = styled.a`
	${lozengeStyles};

	&:focus,
	&:hover {
		background-color: #f4f5f7;
		color: #333;
		text-decoration: none;
	}

	&:active {
		background-color: #e4e5ea;
	}
`;
const lozengeStyles = css`
	display: flex;
	align-items: center;
	padding: 2px 6px;
	border-radius: 3px;
	background-color: #f7f8f9;
`;

// Component using @compiled/react jsx and css
const Component = ({
  children,
  forceMaxWidth
}) => <CC>
    <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _0, _1, _10]}</CS>
    {<div className={ax(["_1e0c1txw _4cvr1h6o _ca0qyh40 _u5f3idpf _n3tdyh40 _19bvidpf _2hwx1y44 _bfhk1kw7 _syaz1d6m", forceMaxWidth && "_1reo15vq _18m915vq _p12fuuw1"])}>
		{children}
	</div>}
  </CC>;

// Component using styled-components
const StyledComponent = styled.div`
	${plainTextStyles};
	${props => props.forceMaxWidth && maxWidth2};
`;
export default Component;
