/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 =
	'@supports not (-moz-appearance:none){._ytfl13q2{color:blue}._10msu67f{background-color:#fff}}';
const _ = '._syaz5scu{color:red}';
const styles = null;
<CC>
	<CS>{[_, _2]}</CS>
	{<div className={ax(['_syaz5scu _ytfl13q2 _10msu67f'])} />}
</CC>;
