/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _3 = '._1fbr5scu .child:hover{color:red}';
const _2 = '._1fbr13q2 .child:hover{color:blue}';
const _ = '._1wybdlk8{font-size:14px}';
const C = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { active, ...__cmpldp } = __cmplp;
	return (
		<CC>
			<CS>{[_, _2, _3]}</CS>
			<C
				{...__cmpldp}
				style={__cmpls}
				ref={__cmplr}
				className={ax(['_1wybdlk8', __cmplp.active ? '_1fbr13q2' : '_1fbr5scu', __cmplp.className])}
			/>
		</CC>
	);
});
if (process.env.NODE_ENV !== 'production') {
	C.displayName = 'C';
}
export const View = () => <C />;
