/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _4 = '._30l313q2:hover{color:blue}';
const _3 = '._f8pjbf54:focus{color:green}';
const _2 = '._aetrb3bt:after{content:""}';
const _ = '._syaz5scu{color:red}';
const styles = null;
<CC>
	<CS>{[_, _2, _3, _4]}</CS>
	{<div className={ax(['_syaz5scu _aetrb3bt _f8pjbf54 _30l313q2'])} />}
</CC>;
