/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _14 = "._o5721q9c{white-space:nowrap}";
const _13 = "._1p1dangw{text-transform:uppercase}";
const _12 = "._1bto1l2s{text-overflow:ellipsis}";
const _11 = "._vwz47vkz{line-height:1pc}";
const _10 = "._k48p8n31{font-weight:bold}";
const _1 = "._zg8l4jg8{font-style:normal}";
const _0 = "._1wyb1skh{font-size:11px}";
const _9 = "._ect49sn6{font-family:ui-sans-serif}";
const _8 = "._vchhusvi{box-sizing:border-box}";
const _7 = "._kqswpfqs{position:static}";
const _6 = "._1kz6184x{block-size:min-content}";
const _5 = "._1e0c116y{display:inline-flex}";
const _4 = "._18zr1y44{padding-inline:4px}";
const _3 = "._18m915vq{overflow-y:hidden}";
const _2 = "._1reo15vq{overflow-x:hidden}";
const _ = "._2rko1l7b{border-radius:3px}";
const styles = {
  container: "_2rko1l7b _1reo15vq _18m915vq _18zr1y44 _1e0c116y _1kz6184x _kqswpfqs _vchhusvi",
  text: "_1reo15vq _18m915vq _ect49sn6 _1wyb1skh _zg8l4jg8 _k48p8n31 _vwz47vkz _1bto1l2s _1p1dangw _o5721q9c"
};
export const Component = () => <CC>
    <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _0, _1, _10, _11, _12, _13, _14]}</CS>
    {<div className={ax([styles.container])}>
    <CC>
    <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _0, _1, _10, _11, _12, _13, _14]}</CS>
    {<span className={ax([styles.text])}>Hello</span>}
  </CC>
  </div>}
  </CC>;
