/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
import { xcss } from '@atlaskit/primitives';
const shimmer = null;
const styles = xcss({
  width: '100%',
  animation: `${shimmer} 1s infinite`,
  background: 'red'
});
export const Component = () => <div xcss={styles} />;
