[package]
name = "atlaspack_swc_runner"
version = "0.1.0"
edition = { workspace = true }
description = "SWC runner functions for Atlaspack"

[lints]
workspace = true

[dependencies]
regex = { workspace = true }
swc_core = { workspace = true, features = [
    "base",
    "__ecma",
    "ecma_codegen",
    "__visit",
    "__parser",
    "ecma_ast",
    "__common",
    "__testing_transform",
    "common_sourcemap"
]}
serde_json = { workspace = true }
thiserror = { workspace = true }
swc_ecma_parser = { workspace = true }
sourcemap = { workspace = true }

#atlaspack-js-swc-core = { path = "../../packages/transformers/js/core" }
