[package]
name = "atlaspack_swc_runner"
version = "0.1.0"
edition = "2021"
description = "SWC runner functions for Atlaspack"

[dependencies]
regex = { workspace = true }
swc_core = { workspace = true }
thiserror = { workspace = true }
swc_ecma_parser = { workspace = true }
sourcemap = { workspace = true }

#atlaspack-js-swc-core = { path = "../../packages/transformers/js/core" }
