/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '._vwz4cjiy{line-height:1.2}';
const _ = '._1yyj1l7b{-webkit-line-clamp:3px}';
const styles = null;
<CC>
	<CS>{[_, _2]}</CS>
	{<div className={ax(['_1yyj1l7b _vwz4cjiy'])} />}
</CC>;
