/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _6 = "@media not all and (min-width:48rem){._suga19ly{display:revert}}";
const _5 = "@media not all and (min-width:30rem){._1m0a19ly{display:revert}}";
const _4 = "@media (min-width:64rem){._dm2519ly{display:revert}}";
const _3 = "@media (min-width:48rem){._181n19ly{display:revert}}";
const _2 = "@media (min-width:30rem){._114b19ly{display:revert}}";
const _ = "._1e0cglyw{display:none}";
const styles = {
  default: "_1e0cglyw",
  'above.xs': "_114b19ly",
  'above.sm': "_181n19ly",
  'above.md': "_dm2519ly",
  'below.xs': "_1m0a19ly",
  'below.sm': "_suga19ly"
};
export const Component = ({
  above,
  below,
  children
}) => {
  return <CC>
    <CS>{[_, _2, _3, _4, _5, _6]}</CS>
    {<div className={ax([styles.default, above && styles[`above.${above}`], below && styles[`below.${below}`]])}>
      {children}
    </div>}
  </CC>;
};
