/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _4 = "._4cvr1q9y{align-items:baseline}";
const _3 = "._1e0c1ule{display:block}";
const _2 = "._2lx21bp4{flex-direction:column}";
const _ = "._1e0c1txw{display:flex}";
const bodyStyles = null;
const imageStyles = null;
const defaultHeaderStyles = null;
const Component = () => <CC>
    <CS>{[_, _2]}</CS>
    {<div className={ax(["_1e0c1txw _2lx21bp4"])}>
    <CC>
    <CS>{[_3]}</CS>
    {<img src="test.jpg" alt="" className={ax(["_1e0c1ule"])} />}
  </CC>
    <CC>
    <CS>{[_, _4]}</CS>
    {<div className={ax(["_1e0c1txw _4cvr1q9y"])}>Header</div>}
  </CC>
  </div>}
  </CC>;
export default Component;
