/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _7 = "._30l3bf54:hover{color:green}";
const _6 = "._bfhk13q2{background-color:blue}";
const _5 = "._syaz5scu{color:red}";
const _4 = "._19bvftgi{padding-left:8px}";
const _3 = "._n3tdftgi{padding-bottom:8px}";
const _2 = "._u5f3ftgi{padding-right:8px}";
const _ = "._ca0qftgi{padding-top:8px}";
function Component() {
  return <CC>
    <CS>{[_, _2, _3, _4, _5, _6, _7]}</CS>
    {<div className={ax(["_ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi _syaz5scu _bfhk13q2 _30l3bf54"])}>
      Hello World
    </div>}
  </CC>;
}
