/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { forwardRef } from 'react';
import { token } from '@atlaskit/tokens';
const _ = "._1yt4mtij{padding:var(--ds-space-050,4px) var(--ds-space-150,9pt) var(--ds-space-150,9pt) var(--_udlqo0)}";
const Wrapper = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_]}</CS>
        <C {...__cmplp} style={{ ...__cmpls, "--_udlqo0": ix(__cmplp.padded ? token('space.150') : token('space.0')) }} ref={__cmplr} className={ax(["_1yt4mtij", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Wrapper.displayName = 'Wrapper';
}
export const Component = () => <Wrapper padded />;
