/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _ = '._syaz13q2{color:blue}';
<>
	<CC>
		<CS>{[_]}</CS>
		{<div className={ax(['_syaz13q2'])} />}
	</CC>
	<CC>
		<CS>{[_]}</CS>
		{<div className={ax(['_syaz13q2', cx('A', 'B')])} />}
	</CC>
</>;
