/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const CSS_VAR_ICON_COLOR = '--flag-icon-color';
const descriptionStyles = {};
const iconWrapperStyles = {};
const flagWrapperStyles = {};
const analyticsAttributes = {
  componentName: 'flag',
  packageName: 'test',
  packageVersion: '1.0.0'
};
function Flag() {
  return <div>
            <span>Content</span>
            <div>Test</div>
        </div>;
}
export default Flag;
