[package]
name = "atlaspack_plugin_transformer_yaml"
version = "0.1.0"
authors = ["Monica Olejniczak <monica.j.olejniczak@gmail.com>"]
edition = "2021"
description = "Yaml transformer plugin for the Atlaspack Bundler"

[dependencies]
atlaspack_core = { path = "../atlaspack_core" }

anyhow = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
serde_yml = { workspace = true }

[dev-dependencies]
atlaspack_filesystem = { path = "../atlaspack_filesystem" }
pretty_assertions = { workspace = true }
tokio = { workspace = true, features = ["full"] }
