/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _3 = "._ajmmnqa1{text-decoration-style:solid}";
const _2 = "._1hmsglyw{text-decoration-line:none}";
const _ = "._4bfu1r31{text-decoration-color:currentColor}";
const base = null;
export const Component = () => <CC>
  <CS>{[_, _2, _3]}</CS>
  {<div className={ax(["_4bfu1r31 _1hmsglyw _ajmmnqa1"])}>
    Hello
  </div>}
</CC>;
