/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '._j7hq1wwu{animation-name:kgnpaw5}';
const _ = '@keyframes kgnpaw5{0%{opacity:0}to{opacity:1}}';
const moveFade = null;
<CC>
	<CS>{[_, _2]}</CS>
	{<div className={ax(['_j7hq1wwu'])} />}
</CC>;
