/* in.jsx generated by @compiled/babel-plugin */
import * as React from 'react';
import { CC, CS, ax, ix } from "@compiled/react/runtime";
const _ = "._1py05scu>[data-test]{color:red}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_1py05scu"])} />}
</CC>;
