/* in.jsx generated by @compiled/babel-plugin */
import { CC, CS, ax, ix } from "@compiled/react/runtime";
import * as React from 'react';
import { forwardRef } from 'react';
const _ = "._189ee4h9{border-width:var(--ds-border-width,1px)}";
const _1 = "._1h6dmuej{border-color:var(--ds-border,#091e4224)}";
const _2 = "._19bvutpp{padding-left:var(--ds-space-150,9pt)}";
const _3 = "._24rcu2gc >span{margin-left:var(--ds-space-100,8px)}";
const Component = /*#__PURE__*/forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
      <CS>{[_, _1, _2, _3]}</CS>
      {<C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_189ee4h9 _1h6dmuej _19bvutpp _24rcu2gc", __cmplp.className])} />}
    </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Component.displayName = 'Component';
}
export const Example = () => <Component>
    <span>Child</span>
  </Component>;
