[package]
name = "caniuse_database"
version = "0.1.0"
edition = "2021"

[dependencies]
browserslist-rs = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
tinyvec = { workspace = true, features = ["alloc", "serde"] }
serde = { workspace = true }
serde_json = { workspace = true }
