/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { padding, outline } from './external';
const _ = "._1yt46fkr{padding:var(--_1xumd0e) var(--_oex9l5) 0 0}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_1yt46fkr"])} style={{
    "--_1xumd0e": ix(padding),
    "--_oex9l5": ix(outline)
  }} />}
</CC>;
