/* in.jsx generated by @compiled/babel-plugin */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { jsx, jsxs } from "react/jsx-runtime";
const _ = "._syazieo0{color:var(--project-color-text)}";
const Wrapper = ({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}) => <CC>
  <CS>{[_]}</CS>
  <C
    {...__cmplp}
    style={__cmpls}
    className={ax([!__cmplp.withSidebar && "_syazieo0", __cmplp.className])}
  />
</CC>;
export const Component = ({
  withSidebar
}) => <Wrapper withSidebar={withSidebar} />;
