/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { layers } from '@atlassian/jira-common-styles/src/main.tsx';
const _ = "._1pbybfng{z-index:500}";
const _1 = "._kqsw1n9t{position:fixed}";
const Wrapper = forwardRef(({ as: C = "div", style: __cmpls, ...__cmplp }, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _1]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1pbybfng _kqsw1n9t", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Wrapper.displayName = 'Wrapper';
}
export const Component = () => <Wrapper />;
