/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _11 = "._bfhk17nt{background-color:gray}";
const _10 = "._bfhk13q2{background-color:blue}";
const _1 = "._16l4txnc:hover{opacity:.8}";
const _0 = "._j5dh13gf:disabled{cursor:not-allowed}";
const _9 = "._1j55105o:disabled{opacity:.5}";
const _8 = "._80omtlke{cursor:pointer}";
const _7 = "._syazu67f{color:#fff}";
const _6 = "._2rko1y44{border-radius:4px}";
const _5 = "._19itglyw{border:none}";
const _4 = "._19bv7vkz{padding-left:1pc}";
const _3 = "._n3tdftgi{padding-bottom:8px}";
const _2 = "._u5f37vkz{padding-right:1pc}";
const _ = "._ca0qftgi{padding-top:8px}";
const StyledButton = forwardRef(({
  as: C = "button",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    primary,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _0, _1, _10, _11]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_ca0qftgi _u5f37vkz _n3tdftgi _19bv7vkz _19itglyw _2rko1y44 _syazu67f _80omtlke _1j55105o _j5dh13gf _16l4txnc", __cmplp.primary ? "_bfhk13q2" : "_bfhk17nt", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StyledButton.displayName = 'StyledButton';
}
export const Component = ({
  primary,
  disabled,
  children,
  ...props
}) => {
  return <StyledButton primary={primary} disabled={disabled} {...props}>
      {children}
    </StyledButton>;
};
