/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _4 =
	'@media (min-width:64rem){._2oz4ftgi{border-radius:8px}._maar13q2{color:blue}._4ap3u67f{background-color:#fff}}';
const _3 = '._bfhkr3uz{background-color:#000}';
const _2 = '._syaz5scu{color:red}';
const _ = '._2rko1y44{border-radius:4px}';
const styles = null;
<CC>
	<CS>{[_, _2, _3, _4]}</CS>
	{<div className={ax(['_2rko1y44 _syaz5scu _bfhkr3uz _2oz4ftgi _maar13q2 _4ap3u67f'])} />}
</CC>;
