/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _3 = "._otyrftgi{margin-bottom:8px}";
const _2 = "._19pk7vkz{margin-top:1pc}";
const _ = "._19pk1tcg{margin-top:24px}";
const titleStyles = {
  root: "_otyrftgi"
};
const FeatureCard = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_19pk1tcg", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  FeatureCard.displayName = 'FeatureCard';
}
const ButtonContainer = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_2]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_19pk7vkz", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  ButtonContainer.displayName = 'ButtonContainer';
}
function FeatureCardView({
  title,
  description
}) {
  return <FeatureCard>
      <CC>
    <CS>{[_3]}</CS>
    {<div className={ax([titleStyles.root])}>
        <h3>{title}</h3>
      </div>}
  </CC>
      <div>{description}</div>
      <ButtonContainer>
        <button>Learn More</button>
      </ButtonContainer>
    </FeatureCard>;
}
export default FeatureCardView;
