/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _3 = "._1q7w1isi span:before{content:attr(data-label)}";
const _2 = "._aetr1e8g:after{content:\"hello\"}";
const _ = "._1kt9b3bt:before{content:\"\"}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2, _3]}</CS>
  {<div className={ax(["_1kt9b3bt _aetr1e8g _1q7w1isi"])}>
    <span data-label="test" />
  </div>}
</CC>;
