/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { mq } from './breakpoints';
const _ = "@media (min-width:30em){._qhso1cnh{color:purple}}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_qhso1cnh"])}>Hello</div>}
</CC>;
