/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { palette } from './palette';
const _2 = "._irr3u67f:hover{background-color:#fff}";
const _ = "._syaz1ejv{color:rgba(10,20,30,.8)}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2]}</CS>
  {<div className={ax(["_syaz1ejv _irr3u67f"])}>
    imported twice
  </div>}
</CC>;
