/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._bfhk1n88{background-color:#f5f5f5}";
const _ = "._syaz15td{color:#639}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2]}</CS>
  {<div className={ax(["_syaz15td _bfhk1n88", "legacy"])}>
    hello world
  </div>}
</CC>;
