/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _4 = '@media (min-width:600px){._10s75scu{color:red}}';
const _3 = '@media (min-width:600px){._10s713q2{color:blue}}';
const _2 = '@media (min-width:600px){}';
const _ = '._1wyb19bv{font-size:10px}';
const C = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { isPrimary, ...__cmpldp } = __cmplp;
	return (
		<CC>
			<CS>{[_, _2, _3, _4]}</CS>
			<C
				{...__cmpldp}
				style={__cmpls}
				ref={__cmplr}
				className={ax([
					'_1wyb19bv',
					__cmplp.isPrimary ? '_10s713q2' : '_10s75scu',
					__cmplp.className,
				])}
			/>
		</CC>
	);
});
if (process.env.NODE_ENV !== 'production') {
	C.displayName = 'C';
}
export const View = () => <C />;
