/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '@keyframes kgnpaw5{0%{opacity:0}to{opacity:1}}';
const _ = '._j7hq1wwu{animation-name:kgnpaw5}';
const fade = null;
const Button = forwardRef(({ as: C = 'button', style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	return (
		<CC>
			<CS>{[_, _2]}</CS>
			<C
				{...__cmplp}
				style={__cmpls}
				ref={__cmplr}
				className={ax(['_j7hq1wwu', __cmplp.className])}
			/>
		</CC>
	);
});
if (process.env.NODE_ENV !== 'production') {
	Button.displayName = 'Button';
}
console.log(Button);
