/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '._4t3ivxtu{height:var(--_6olcn1)}';
const _ = '._1bsbvxtu{width:var(--_6olcn1)}';
export const View = () => (
	<CC>
		<CS>{[_, _2]}</CS>
		{
			<div
				className={ax(['_1bsbvxtu _4t3ivxtu'])}
				style={{
					'--_6olcn1': ix(Math.random() + 'px'),
				}}
			/>
		}
	</CC>
);
