/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._y44v16rn{animation:kgnpaw5 1s ease}";
const _ = "@keyframes kgnpaw5{0%{opacity:0}to{opacity:1}}";
const fadeIn = null;
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2]}</CS>
  {<div className={ax(["_y44v16rn"])}>Hello</div>}
</CC>;
