[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "atlaspack-macros"
version = "0.1.0"
edition = "2021"

[features]
napi = ["dep:napi", "dep:napi-derive", "dep:crossbeam-channel"]

[dependencies]
indexmap = { workspace = true }
swc_core = { workspace = true, features = [
  "common",
  "common_ahash",
  "common_sourcemap",
  "ecma_ast",
  "ecma_parser",
  "ecma_visit",
  "stacker",
  "__utils"
] }
serde = { workspace = true }
napi-derive = { workspace = true, optional = true }
napi = { workspace = true, features = ["serde-json", "napi4", "napi5"], optional = true }
crossbeam-channel = { workspace = true, optional = true }
