/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '._j7hqbunn{animation-name:ky1j872}';
const _ =
	'@keyframes ky1j872{0%{color:blue;opacity:var(--_19i50d6)}to{color:indigo;opacity:var(--_1mdpi68)}}';
const runtime = {
	colors: {
		blue: 'blue',
		indigo: 'indigo',
	},
	enabled: true,
};
const getOpacity = (x) => (runtime.enabled ? x : 1);
const fadeOut = null;
export const View = () => (
	<CC>
		<CS>{[_, _2]}</CS>
		{
			<div
				className={ax(['_j7hqbunn'])}
				style={{
					'--_19i50d6': ix(getOpacity(0)),
					'--_1mdpi68': ix(getOpacity(1)),
				}}
			/>
		}
	</CC>
);
