/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _0 = "._jk43mw0c:focus-within:before{box-shadow:inset 0 0 0 2px blue}";
const _9 = "._kfgt1osq:before{height:100%}";
const _8 = "._1mp41osq:before{width:100%}";
const _7 = "._1cs8stnw:before{position:absolute}";
const _6 = "._1kt9b3bt:before{content:\"\"}";
const _5 = "._kqswh2mm{position:relative}";
const _4 = "._18u0ftgi{margin-left:8px}";
const _3 = "._otyrftgi{margin-bottom:8px}";
const _2 = "._2hwxftgi{margin-right:8px}";
const _ = "._19pkftgi{margin-top:8px}";
const styles = {
  base: "_19pkftgi _2hwxftgi _otyrftgi _18u0ftgi _kqswh2mm _1kt9b3bt _1cs8stnw _1mp41osq _kfgt1osq _jk43mw0c"
};
export const Component = () => <CC>
  <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _0]}</CS>
  {<div className={ax([styles.base])}>pseudo</div>}
</CC>;
