/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _16 = "._1ko9idpf >*{margin-left:0}";
const _15 = "._d4l7idpf >*{margin-right:0}";
const _14 = "._1ko91l7b >*{margin-left:3px}";
const _13 = "._8jx7idpf >*{margin-bottom:0}";
const _12 = "._d4l71l7b >*{margin-right:3px}";
const _11 = "._1mizidpf >*{margin-top:0}";
const _10 = "._irr318uv:hover{background-color:initial}";
const _1 = "._jomr18uv:focus{background-color:initial}";
const _0 = "._irr35scu:hover{background-color:red}";
const _9 = "._jomr5scu:focus{background-color:red}";
const _8 = "._80om1wug{cursor:auto}";
const _7 = "._80omtlke{cursor:pointer}";
const _6 = "._4hz81o36:hover{outline-width:medium}";
const _5 = "._1hvw1o36:focus{outline-width:medium}";
const _4 = "._ksodglyw:hover{outline-style:none}";
const _3 = "._49pcglyw:focus{outline-style:none}";
const _2 = "._1dit1r31:hover{outline-color:currentColor}";
const _ = "._nt751r31:focus{outline-color:currentColor}";
const Item = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isClickable,
    spaced,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _0, _1, _10, _11, _12, _13, _14, _15, _16]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_nt751r31 _1dit1r31 _49pcglyw _ksodglyw _1hvw1o36 _4hz81o36", __cmplp.isClickable ? "_80omtlke" : "_80om1wug", __cmplp.isClickable ? "_jomr5scu _irr35scu" : "_jomr18uv _irr318uv", __cmplp.spaced ? "_1mizidpf _d4l71l7b _8jx7idpf _1ko91l7b" : "_1mizidpf _d4l7idpf _8jx7idpf _1ko9idpf", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Item.displayName = 'Item';
}
export const Component = ({
  isClickable,
  spaced
}) => <Item isClickable={isClickable} spaced={spaced}>
    Content
  </Item>;
