/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { forwardRef } from 'react';
import { token } from '@atlaskit/tokens';
const _ = "._ppen1fxt >input::placeholder{color:var(--ds-text,#172b4d)}";
const _1 = "._ajcj1wq8 >input::placeholder{font-weight:var(--ds-font-weight-medium,500)}";
const Wrapper = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr)=>{
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[
        _,
        _1
      ]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_ppen1fxt _ajcj1wq8", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Wrapper.displayName = 'Wrapper';
}
export const Component = ()=><Wrapper><input placeholder="Example" /></Wrapper>;
