/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _5 = '._syaz5scu{color:red}';
const _4 = '._18u019bv{margin-left:10px}';
const _3 = '._otyr19bv{margin-bottom:10px}';
const _2 = '._2hwx19bv{margin-right:10px}';
const _ = '._19pk19bv{margin-top:10px}';
const styles = null;
<CC>
	<CS>{[_, _2, _3, _4, _5]}</CS>
	{<div className={ax(['_19pk19bv _2hwx19bv _otyr19bv _18u019bv _syaz5scu'])} />}
</CC>;
