/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _3 = "._5sag9cwz{animation-duration:1s}";
const _2 = "._j7hq1en8{animation-name:k6xje6p}";
const _ = "@keyframes k6xje6p{0%{background-position:-300px 0}to{background-position:750pt 0}}";
const shimmer = null;
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2, _3]}</CS>
  {<div className={ax(["_j7hq1en8 _5sag9cwz"])} />}
</CC>;
