name: Setup watchman
description: Setup watchman

runs:
  using: composite
  steps:
    - name: Install watchman with brew
      run: brew install watchman
      shell: bash
      if: ${{ runner.os == 'macOS' }}

    - name: Install watchman from a binary
      run: |
        apt install -y watchman

      shell: bash
      if: ${{ runner.os == 'Linux' }}

    - name: Run watchman version
      run: watchman --version
      shell: bash
