name: Setup watchman
description: Setup watchman

runs:
  using: composite
  steps:
    - name: Install watchman with brew
      run: brew install watchman
      shell: bash
      if: ${{ runner.os == 'macOS' }}

    - name: Install watchman from a binary
      run: |
        WATCHMAN_VERSION="2025.05.26.00"
        curl -L -O https://github.com/facebook/watchman/releases/download/v${WATCHMAN_VERSION}/watchman-v${WATCHMAN_VERSION}-linux.zip
        unzip watchman-v${WATCHMAN_VERSION}-linux.zip
        echo "$PWD/watchman-v${WATCHMAN_VERSION}-linux/bin" >> $GITHUB_PATH

        mkdir -p /usr/local/{bin,lib} /usr/local/var/run/watchman
        cp bin/* /usr/local/bin
        cp lib/* /usr/local/lib
        chmod 755 /usr/local/bin/watchman
        chmod 2777 /usr/local/var/run/watchman

      shell: bash
      if: ${{ runner.os == 'Linux' }}

    - name: Run watchman version
      run: watchman --version
      shell: bash
