/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _4 = '._bfhk5scu{background-color:red}';
const _3 = '._syaz13q2{color:blue}';
const _2 = '._bfhk13q2{background-color:blue}';
const _ = '._syaz5scu{color:red}';
const styles = null;
const stylesMap = {
	primary: '_syaz5scu _bfhk13q2',
	secondary: '_syaz13q2 _bfhk5scu',
};
const div = (
	<CC>
		<CS>{[_, _2, _3, _4]}</CS>
		{<div className={ax(['_syaz5scu _bfhk13q2', stylesMap.primary])} />}
	</CC>
);
