/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _3 = "._1o9zidpf{flex-shrink:0}";
const _2 = "._1bsb1rkg{width:var(--_1gljcou)}";
const _ = "._v5641gda{transition:var(--_lbjvny)}";
const Wrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    duration,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_1gljcou": ix(__cmplp.width),
      "--_lbjvny": ix(`width ${__cmplp.duration}ms ease`)
    }} ref={__cmplr} className={ax(["_v5641gda _1bsb1rkg _1o9zidpf", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Wrapper.displayName = 'Wrapper';
}
export const Component = () => <Wrapper width="120px" duration={200} />;
