[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "atlaspack-node-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
canary = ["atlaspack_monitoring/canary"]

[dependencies]
atlaspack = { path = "../atlaspack" }
atlaspack_core = { path = "../atlaspack_core" }
atlaspack-js-swc-core = { path = "../../packages/transformers/js/core" }
atlaspack_monitoring = { path = "../atlaspack_monitoring" }
atlaspack-resolver = { path = "../../packages/utils/node-resolver-rs" }
atlaspack_package_manager = { path = "../atlaspack_package_manager" }
atlaspack_plugin_optimizer_inline_requires = { path = "../atlaspack_plugin_optimizer_inline_requires" }
atlaspack_plugin_transformer_js = { path = "../atlaspack_plugin_transformer_js" }
atlaspack_napi_helpers = { path = "../atlaspack_napi_helpers" }
atlaspack_vcs = { path = "../atlaspack_vcs" }
atlaspack_swc_runner = { path = "../atlaspack_swc_runner" }
lmdb-js-lite = { path = "../lmdb-js-lite" }

anyhow = { workspace = true }
glob = { workspace = true }
log = { workspace = true }
mockall = { workspace = true }
napi-derive = { workspace = true }
num_cpus = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
xxhash-rust = { workspace = true, features = ["xxh3"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
atlaspack = { path = "../atlaspack", features = ["nodejs"] }
atlaspack-dev-dep-resolver = { path = "../../packages/utils/dev-dep-resolver" }
atlaspack-macros = { path = "../macros", features = ["napi"] }

crossbeam-channel = { workspace = true }
indexmap = { workspace = true }
libc = { workspace = true }
mozjpeg-sys = { workspace = true }
napi = { workspace = true, features = ["async", "napi4", "napi5", "serde-json"] }
once_cell = { workspace = true }
oxipng = { workspace = true }
rayon = { workspace = true }
swc_core = { workspace = true }

# Crash reporting dependencies

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["custom"], default-features = false }
napi = { workspace = true, features = ["serde-json"] }

[target.'cfg(all(target_os = "macos", not(feature = "canary")))'.dependencies]
# jemallocator is disabled on canary builds to experiment with its performance
# and reliability
jemallocator = { workspace = true, features = ["disable_initial_exec_tls"] }

[target.'cfg(windows)'.dependencies]
mimalloc = { workspace = true, default-features = false }

[build-dependencies]
napi-build = { workspace = true }
