/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _5 = '._bfhk32ev{background-color:pink}';
const _4 = '._4t3i11to{height:var(--_rtjbho)}';
const _3 = '._p12f1rkg{max-width:var(--_1gljcou)}';
const _2 = '._1ul91rkg{min-width:var(--_1gljcou)}';
const _ = '._1bsb1dfw{width:var(--_1d9trqz)}';
export const Complex = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { dim, ...__cmpldp } = __cmplp;
	return (
		<CC>
			<CS>{[_, _2, _3, _4, _5]}</CS>
			<C
				{...__cmpldp}
				style={{
					...__cmpls,
					'--_1d9trqz': ix(__cmplp.dim.width + 10 + 'px'),
					'--_1gljcou': ix(__cmplp.width),
					'--_rtjbho': ix(__cmplp.dim.height),
				}}
				ref={__cmplr}
				className={ax(['_1bsb1dfw _1ul91rkg _p12f1rkg _4t3i11to _bfhk32ev', __cmplp.className])}
			/>
		</CC>
	);
});
if (process.env.NODE_ENV !== 'production') {
	Complex.displayName = 'Complex';
}
export const View = () => <Complex />;
