/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { color } from './tokens';
const _ = "._syaz13q2{color:blue}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_syaz13q2"])}>Hello</div>}
</CC>;
