/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.Component = void 0;
var _react = require("react");
var _runtime = require("@compiled/react/runtime");
var _jsxRuntime = require("react/jsx-runtime");
const _ = "._bfhkmoow{background-color:var(--_qn7x4k)}";
const Component = exports.Component = (0, _react.forwardRef)(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isRowSelected,
    formatRuleBackgroundColor,
    ...__cmpldp
  } = __cmplp;
  return /*#__PURE__*/(0, _jsxRuntime.jsxs)(_runtime.CC, {
    children: [/*#__PURE__*/(0, _jsxRuntime.jsx)(_runtime.CS, {
      nonce: "k0Mp1lEd",
      children: [_]
    }), /*#__PURE__*/(0, _jsxRuntime.jsx)(C, {
      ...__cmpldp,
      style: {
        ...__cmpls,
        "--_qn7x4k": (0, _runtime.ix)((() => {
          // Nested ternary operator is needed, otherwise there's a bug that the first token is applied regardless of condition
          // eslint-disable-next-line no-nested-ternary
          return __cmplp.isRowSelected ? "var(--ds-background-selected, #E9F2FF)" : __cmplp.formatRuleBackgroundColor ? __cmplp.formatRuleBackgroundColor : "var(--ds-background-neutral-subtle, #00000000)";
        })())
      },
      ref: __cmplr,
      className: (0, _runtime.ax)(["_bfhkmoow", __cmplp.className])
    })]
  });
});
if (process.env.NODE_ENV !== 'production') {
  Component.displayName = 'Component';
}
