/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ac, ix, CC, CS } from "@compiled/react/runtime";
const _ = ".a{font-size:9pt}";
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ac(["_1wyb_a"])} />}
</CC>;
