/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _ = '._19it1d5y{border:1px solid var(--green)}';
const styles = null;
<CC>
	<CS>{[_]}</CS>
	{<div className={ax(['_19it1d5y'])} />}
</CC>;
