/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
import { jsx } from "react/jsx-runtime";
import { colors } from '@atlaskit/theme';
const Box = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_bfhku67f _syazalr3", __cmplp.className])} />;
});
if (process.env.NODE_ENV !== 'production') {
  Box.displayName = 'Box';
}
export const Component = () => <Box>Hi</Box>;
