/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '@property --x{syntax:<number>;inherits:var(--_ikpmwb);initial-value:0}';
const _ = '._syaz5scu{color:red}';
const styles = null;
<CC>
	<CS>{[_, _2]}</CS>
	{
		<div
			className={ax(['_syaz5scu'])}
			style={{
				'--_ikpmwb': ix(false),
			}}
		/>
	}
</CC>;
