/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _6 = '._30l3r3uz:hover{color:#000}';
const _5 = '._bfhkr75e{background-color:#eee}';
const _4 = '._syaz13q2{color:blue}';
const _3 = '._30l313q2:hover{color:blue}';
const _2 = '._bfhku67f{background-color:#fff}';
const _ = '._syaz5scu{color:red}';
const variants = {
	primary: '_syaz5scu _bfhku67f _30l313q2',
	secondary: '_syaz13q2 _bfhkr75e _30l3r3uz',
};
<>
	<CC>
		<CS>{[_, _2, _3, _4, _5, _6]}</CS>
		{<div className={ax([variants.primary])} />}
	</CC>
	<CC>
		<CS>{[_, _2, _3, _4, _5, _6]}</CS>
		{<div className={ax([variants.secondary])} />}
	</CC>
</>;
