/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _3 = '._j7hq17bf{animation-name:k1sa9y38}';
const _2 = '@keyframes k1sa9y38{0%{opacity:0}to{opacity:1}}';
const _ = '._syaz5scu{color:red}';
const Comp = () => {
	return (
		<CC>
			<CS>{[_, _2, _3]}</CS>
			{<div className={ax(['_syaz5scu', '_j7hq17bf'])} />}
		</CC>
	);
};
