/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix } from "@compiled/react/runtime";
const styles = {
  base: "_syaz5scu _30l313q2"
};
export const Component = () => <div className={styles.base}>hello</div>;
