/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._osiy1r8g >*{flex-basis:var(--ds-space-500,40px)}";
const _ = "._osiyu43s >*{flex-basis:var(--ds-space-200,1pc)}";
const ListItem = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isCompact,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["", __cmplp.isCompact ? "_osiyu43s" : "_osiy1r8g", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  ListItem.displayName = 'ListItem';
}
export const Component = ({
  isCompact
}) => <ListItem isCompact={isCompact}>
    <div>Content</div>
  </ListItem>;
