/* in.jsx generated by @compiled/babel-plugin */
import { CC, CS, ax, ix } from "@compiled/react/runtime";
import * as React from 'react';
const _ = "._w8uegrho{--example-height:0px}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_w8uegrho"])} />}
</CC>;
