/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _5 = '._syaz13q2{color:blue}';
const _4 = '._bfhk13q2{background-color:blue}';
const _3 = '._syaz5scu{color:red}';
const _2 = '._bfhku67f{background-color:#fff}';
const _ = '._19it1fqi{border:3px solid #ff0}';
const Component = forwardRef(({ as: C = 'div', style: __cmpls, ...__cmplp }, __cmplr) => {
	if (__cmplp.innerRef) {
		throw new Error("Please use 'ref' instead of 'innerRef'.");
	}
	const { isPrimary, ...__cmpldp } = __cmplp;
	return (
		<CC>
			<CS>{[_, _2, _3, _4, _5]}</CS>
			<C
				{...__cmpldp}
				style={__cmpls}
				ref={__cmplr}
				className={ax([
					'_19it1fqi _bfhku67f _syaz5scu',
					__cmplp.isPrimary && '_bfhk13q2 _syaz13q2',
					__cmplp.className,
				])}
			/>
		</CC>
	);
});
if (process.env.NODE_ENV !== 'production') {
	Component.displayName = 'Component';
}
export const View = () => <Component />;
