/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _4 = '._syaz14zx{color:crimson}';
const _3 = '._bfhkr75e{background-color:#eee}';
const _2 = '._30l313q2:hover{color:blue}';
const _ = '._syaz5scu{color:red}';
const isActive = true;
const count = 1;
const themes = {
	primary: '_syaz5scu _30l313q2',
	secondary: '_bfhkr75e',
	danger: '_syaz14zx',
};
<>
	<CC>
		<CS>{[_, _2, _3, _4]}</CS>
		{<div className={ax([themes.primary])} />}
	</CC>
	<CC>
		<CS>{[_, _2, _3, _4]}</CS>
		{<div className={ax([themes.primary, isActive && themes.secondary])} />}
	</CC>
	<CC>
		<CS>{[_, _2, _3, _4]}</CS>
		{<div className={ax([false && themes.secondary, themes.primary, cx('A')])} />}
	</CC>
	<CC>
		<CS>{[_, _2, _3, _4]}</CS>
		{<div className={ax([themes.secondary, themes.danger, count > 0 && themes.primary])} />}
	</CC>
</>;
