/* in.jsx generated by @compiled/babel-plugin v0.36.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const styles = {
  'above.xs': "_114bglyw",
  'above.sm': "_181nglyw",
  'above.md': "_dm25glyw",
  'above.lg': "_je3oglyw",
  'above.xl': "_1uxvglyw",
  'below.xs': "_1m0aglyw",
  'below.sm': "_sugaglyw",
  'below.md': "_1mjbglyw",
  'below.lg': "_liwcglyw",
  'below.xl': "_14wzglyw"
};
export const Hide = ({
  children
}) => {
  return <div>
			{children}
		</div>;
};
