/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _2 = '._syaz5scu{color:red}';
const _ = 'user';
const _1 = 'user1';
const styles = null;
<CC>
	<CS>{[_2]}</CS>
	{<div className={ax(['_syaz5scu'])} />}
</CC>;
