name: Build Smoke Test Images

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node.js version to build'
        required: true
        default: '18'
        type: choice
        options:
          - '18'
          - '20'
          - '22'
  schedule:
    # Run weekly on Sunday at 00:00 UTC
    - cron: '0 0 * * 0'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/multiarch-node
          platforms: linux/arm/v7,linux/arm64
          push: true
          build-args: |
            NODE_VERSION=${{ github.event.inputs.node_version || '18' }}
          tags: |
            ghcr.io/${{ github.repository }}/multiarch-node:node${{ github.event.inputs.node_version || '18' }}
