name: 'Enforce Changeset'

on: pull_request

jobs:
  enforce-changeset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const { enforceChangeset } = require('./scripts/enforce-changeset.js');
            await enforceChangeset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pullNumber: context.payload.pull_request.number,
              octokit: github
            });
