name: Release

on:
  workflow_call:
    inputs:
      release-command:
        description: 'The command that will release packages as part of the final step'
        required: true
        type: string
      type:
        description: 'The type of release, usually corresponds to the dist-tag'
        required: true
        type: string
      profile:
        description: 'The profile to use when building the native binaries'
        required: false
        default: 'release'
        type: string
    secrets:
      NPM_TOKEN:
        required: true

permissions:
  contents: write # for actions/checkout and adding tag

jobs:
  build-native:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux AMD64
          - name: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

          # Linux ARM64
          - name: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

          # # Linux ARM
          # We don't support 32 bit linux
          # - name: arm-unknown-linux-gnueabihf
          #   os: ubuntu-24.04
          #   target: arm-unknown-linux-gnueabihf
          #   run: apt install -y gcc-arm-linux-gnueabihf

          # MACOS ARM64
          - name: aarch64-apple-darwin
            os: macos-latest
            target: aarch64-apple-darwin

          # MACOS AMD64
          - name: x86_64-apple-darwin
            os: macos-latest
            target: x86_64-apple-darwin
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: ./.github/actions/rust-toolchain
        with:
          targets: ${{ matrix.target }}
      - uses: actions/setup-node@v4
        with: {cache: yarn}
      - uses: Swatinem/rust-cache@v2
        if: ${{ inputs.type != 'latest' }}
        with: {shared-key: '${{ matrix.name }}'}
      - run: yarn install --frozen-lockfile
      - name: Build native packages
        env:
          RUSTUP_TARGET: ${{ matrix.target }}
          CARGO_PROFILE: ${{ inputs.profile }}
        run: yarn build-native
      - name: Extract debug symbols
        run: node "./scripts/debug-symbols.mjs"
        # Upload the entire contents of ./packages for each platform
        # and later combine them to build up the /platform folder
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.target }}
          path: packages/**/*

  build-and-release:
    name: Build and release
    needs:
      - build-native
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - uses: actions/setup-node@v4
        with: {cache: yarn}
      - uses: actions/download-artifact@v4
        with:
          pattern: packages-*
          path: packages
          merge-multiple: true
      - run: yarn install --frozen-lockfile
      - name: Move debug symbols
        if: ${{ inputs.profile == 'canary' }}
        run: |
          mkdir debug-symbols
          find packages -name "*.debug" -exec cp {} debug-symbols/ \;
          find packages -name "*.node" -path "**/DWARF/**" -exec cp {} debug-symbols/ \;
          ls -l debug-symbols
      - name: Upload combined debug symbols artifact
        uses: actions/upload-artifact@v4
        if: ${{ inputs.profile == 'canary' }}
        with:
          name: debug-symbols
          path: debug-symbols/**
      - name: Debug
        run: ls -l packages/*/*/*.node
      - name: Npm
        run: |
          npm config set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
          npm config set registry https://registry.npmjs.org/
      - run: ${{ inputs.release-command }}
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
      - name: Get canary version
        if: ${{ inputs.type == 'canary' }}
        id: canary-version
        run: echo "VERSION_TAG=$(npm show @atlaspack/cli@canary --json | jq .version -r)" >> "$GITHUB_OUTPUT"
      - name: Create tag
        uses: actions/github-script@v5
        if: ${{ inputs.type == 'canary' }}
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.canary-version.outputs.VERSION_TAG }}'.trim(),
              sha: context.sha
            })

  build-and-release-changesets:
    name: Build and release Changesets
    if: github.ref_name == 'main'
    permissions: write-all
    needs:
      - build-native
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with: {cache: yarn}
      - uses: actions/download-artifact@v4
        with:
          pattern: packages-*
          path: packages
          merge-multiple: true
      - run: yarn install --frozen-lockfile
      - uses: changesets/action@v1
        with:
          publish: yarn changesets-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}