name: Deploy REPL

on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy REPL'
        required: true
        type: string
      alias-domains:
        description: 'A list of domains used for the REPL deploymnet'
        required: false
        type: string
    secrets:
      REPL_VERCEL_TOKEN:
        required: true
      REPL_VERCEL_ORG_ID:
        required: true
      REPL_VERCEL_PROJECT_ID:
        required: true

jobs:
  # Deployment steps taken from https://github.com/colinwilson/static-site-to-vercel/blob/master/.github/workflows/deploy-preview.yml
  repl_build:
    name: Build REPL
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 20
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.82.0
          targets: wasm32-unknown-unknown
      - name: Install wasm-opt
        run: |
          curl -L -O https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-linux.tar.gz
          tar -xf binaryen-version_116-x86_64-linux.tar.gz
          echo "$PWD/binaryen-version_116/bin" >> $GITHUB_PATH
      - uses: Swatinem/rust-cache@v2
        with:
          key: wasm
      - name: Bump max inotify watches
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p;
      - run: yarn --frozen-lockfile
      - name: Build native packages
        run: yarn build-native-release
      - run: yarn build
      - run: yarn build-native-wasm
      - run: yarn workspace @atlaspack/repl build
      - name: Start Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          env: ${{ inputs.environment }}
          override: false
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        id: vercel-action
        with:
          alias-domains: ${{ inputs.alias_domains }}
          github-comment: false
          scope: atlaspack
          vercel-args: ${{ inputs.environment == 'Production' && '--prod' || '' }}
          vercel-org-id: ${{ secrets.REPL_VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.REPL_VERCEL_PROJECT_ID }}
          vercel-token: ${{ secrets.REPL_VERCEL_TOKEN }}
          working-directory: packages/dev/repl
      - name: Update Deployment Status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ inputs.environment }}
          override: false
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.vercel-action.outputs.preview-url }}
