name: Tag Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and release the tagged version
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      release-command: yarn release
      type: latest

  repl:
    if: false
    name: Deploy REPL
    uses: ./.github/workflows/repl.yml
    permissions:
      contents: read
      deployments: write
    secrets: inherit
    with:
      environment: Production
