/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from '@compiled/react/runtime';
const _4 = '._30l35scu:hover{color:red}';
const _3 = '._vn89ftgi:focus{border-radius:8px}';
const _2 = '._syaz13q2{color:blue}';
const _ = '._19it19z9{border:1px solid green}';
const a = null;
const b = null;
<>
	<CC>
		<CS>{[_, _2]}</CS>
		{<div className={ax(['_19it19z9 _syaz13q2'])} />}
	</CC>
	<CC>
		<CS>{[_3, _4]}</CS>
		{<div className={ax(['_vn89ftgi _30l35scu'])} />}
	</CC>
</>;
